# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('merchant_id', models.IntegerField()),
                ('state_pol', models.CharField(max_length=32, verbose_name='Estado de la transacci\xf3n.')),
                ('response_code_pol', models.CharField(max_length=255, verbose_name='Codigo de respuesta de PayU.')),
                ('reference_sale', models.CharField(max_length=255, verbose_name='Referencia de la venta.')),
                ('reference_pol', models.CharField(max_length=255, verbose_name='Referencia o n\xfamero de la transacci\xf3n generado en PayU.')),
                ('sign', models.CharField(max_length=255, verbose_name='Firma digital creada para cada uno de las transacciones.')),
                ('extra1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo adicional para enviar informaci\xf3n sobre la compra')),
                ('extra2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo adicional para enviar informaci\xf3n sobre la compra')),
                ('extra3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo adicional para enviar informaci\xf3n sobre la compra')),
                ('payment_method', models.IntegerField(blank=True, null=True, verbose_name='Identificador interno del medio de pago utilizado.')),
                ('payment_method_type', models.IntegerField(blank=True, null=True, verbose_name='Tipo de medio de pago utilizado para el pago')),
                ('installments_number', models.IntegerField(blank=True, null=True, verbose_name='N\xfamero de cuotas en las cuales se difiri\xf3 el pago con tarjeta cr\xe9dito.')),
                ('value', models.CharField(max_length=50, verbose_name='Monto total de la transacci\xf3n')),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('additional_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha en que se realiz\xf3 la transacci\xf3n.')),
                ('currency', models.CharField(max_length=3)),
                ('email_buyer', models.CharField(max_length=255)),
                ('cus', models.CharField(blank=True, max_length=64, null=True, verbose_name='C\xf3digo \xfanico de seguimiento')),
                ('pse_bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del banco, aplica solo para pagos con PSE.')),
                ('test', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='La direcci\xf3n de facturaci\xf3n')),
                ('shipping_address', models.CharField(blank=True, max_length=55, null=True, verbose_name='La direcci\xf3n de entrega de la mercanc\xeda.')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number_ach', models.CharField(blank=True, max_length=36, null=True, verbose_name='Identificador de la transacci\xf3n.')),
                ('account_type_ach', models.CharField(blank=True, max_length=36, null=True, verbose_name='Identificador de la transacci\xf3n.')),
                ('administrative_fee', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor de la tarifa administrativa')),
                ('administrative_fee_base', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor base de la tarifa administrativa')),
                ('administrative_fee_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor del impuesto de la tarifa administrativa')),
                ('airline_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='C\xf3digo de la aerol\xednea')),
                ('attempts', models.IntegerField(blank=True, null=True, verbose_name='Numero de intentos del env\xedo de la confirmaci\xf3n.')),
                ('authorization_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='C\xf3digo de autorizaci\xf3n de la venta')),
                ('bank_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador del banco')),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='La ciudad de facturaci\xf3n.')),
                ('billing_country', models.CharField(blank=True, max_length=2, null=True, verbose_name='El c\xf3digo ISO del pa\xeds asociado a la direcci\xf3n de facturaci\xf3n.')),
                ('commision_pol', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor de la comisi\xf3n')),
                ('commision_pol_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda de la comisi\xf3n')),
                ('customer_number', models.IntegerField(blank=True, null=True, verbose_name='Numero de cliente.')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de la operaci\xf3n.')),
                ('error_code_bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='C\xf3digo de error del banco.')),
                ('error_message_bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje de error del banco')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor de la tasa de cambio.')),
                ('ip', models.CharField(max_length=39, verbose_name='Direcci\xf3n ip desde donde se realiz\xf3 la transacci\xf3n.')),
                ('nickname_buyer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre corto del comprador.')),
                ('nickname_seller', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre corto del vendedor.')),
                ('payment_method_id', models.IntegerField(blank=True, null=True, verbose_name='Identificador del medio de pago.')),
                ('payment_request_state', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado de la solicitud de pago.')),
                ('pseReference1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia no. 1 para pagos con PSE.')),
                ('pseReference2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia no. 2 para pagos con PSE.')),
                ('pseReference3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia no. 3 para pagos con PSE.')),
                ('response_message_pol', models.CharField(max_length=255, verbose_name='El mensaje de respuesta de PAYU.')),
                ('shipping_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='La ciudad de entrega de la mercanc\xeda.')),
                ('shipping_country', models.CharField(blank=True, max_length=2, null=True, verbose_name='El c\xf3digo ISO asociado al pa\xeds de entrega de la mercanc\xeda.')),
                ('transaction_bank_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador de la transacci\xf3n en el sistema del banco.')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador de la transacci\xf3n.')),
                ('payment_method_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de pago con el cual se hizo el pago.')),
                ('validacion', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Confirmaci\xf3n de pago',
                'verbose_name_plural': 'Confirmaciones de pagos',
            },
        ),
    ]
